### PR TITLE
Migrate to Typescript

### PR DESCRIPTION
**Pull request by fedemp**
These PR migrate the source to TS. Tests are not included cause some issues with Webpack.

### CODE REVIEW

**Comment by tony** [comment]
@fedemp FYI: I am going to release 41.2.0 - you may need to rebase soon.

Sorry I have not gotten to this yet!

**Comment by fedemp** [comment]
No problem! 👍

**Comment by tony** [comment]
@fedemp Hm, I have opened this _yet_ (will on the weekend) - but this would have merge conflicts.

image

Do you know how to rebase? Can you take a look?

**Comment by fedemp** [comment]
I've created a new PR. It seems that so many commits makes it impossible to rebase. :)

https://github.com/isaul32/ckeditor5-math/pull/130

**Pull request closed without merging**
