### PR TITLE
Migrate to Typescript

### PR DESCRIPTION
**Pull request by fedemp**
These PR migrate the source to TS. Tests are not included cause some issues with Webpack.

### CODE REVIEW

**Comment by tony** [comment]
Much welcomed!  I will check this over the weekend.

**Comment by tony** [comment]
Am I fine to make commits to this branch?

**Comment by fedemp** [comment]
> Am I fine to make commits to this branch?

Sure. Be my guest. 😃

**Comment by tony** [comment]
@fedemp I've added some commits

Build output when integrating into a custom build, as of [41.2.1-alpha.2](https://www.npmjs.com/package/@isaul32/ckeditor5-math/v/41.2.1-alpha.2):

<details>

```
ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 83:14-20
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(83,15)
      TS2339: Property 'engine' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 84:14-22
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(84,15)
      TS2339: Property 'lazyLoad' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 85:14-27
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(85,15)
      TS2339: Property 'enablePreview' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 88:14-30
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(88,15)
      TS2339: Property 'previewClassName' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 90:14-28
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(90,15)
      TS2339: Property 'popupClassName' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 92:14-32
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(92,15)
      TS2339: Property 'katexRenderOptions' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 105:90-100
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(105,91)
      TS2339: Property 'outputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 105:113-128
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathui.ts(105,114)
      TS2339: Property 'forceOutputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 90:24-39
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(90,25)
      TS2339: Property 'forceOutputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 91:19-29
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(91,20)
      TS2339: Property 'outputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 113:24-39
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(113,25)
      TS2339: Property 'forceOutputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 114:19-29
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(114,20)
      TS2339: Property 'outputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 127:27-36
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(127,28)
      TS2339: Property 'className' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 135:24-39
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(135,25)
      TS2339: Property 'forceOutputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 136:19-29
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(136,20)
      TS2339: Property 'outputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 166:23-38
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(166,24)
      TS2339: Property 'forceOutputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 167:18-28
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(167,19)
      TS2339: Property 'outputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 242:17-23
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(242,18)
      TS2339: Property 'engine' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 243:17-25
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(243,18)
      TS2339: Property 'lazyLoad' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 247:17-33
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(247,18)
      TS2339: Property 'previewClassName' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 248:17-35
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(248,18)
      TS2339: Property 'katexRenderOptions' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts
../../node_modules/@isaul32/ckeditor5-math/src/mathediting.ts 279:23-32
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/mathediting.ts(279,24)
      TS2339: Property 'className' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 4:0-40 8:16-27
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 116:5-11
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(116,6)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 157:4-10
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(157,5)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 159:10-16
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(159,11)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 296:17-23
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(296,18)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 299:14-20
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(299,15)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 303:2-8
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(303,3)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 309:4-10
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(309,5)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 321:2-8
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(321,3)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 322:2-8
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(322,3)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 339:14-20
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(339,15)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts
../../node_modules/@isaul32/ckeditor5-math/src/utils.ts 340:13-19
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/utils.ts(340,14)
      TS2304: Cannot find name 'global'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/mathui.ts 8:0-49 112:22-44
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 3:0-30 8:29-35
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/automath.ts
../../node_modules/@isaul32/ckeditor5-math/src/automath.ts 122:23-33
[tsl] ERROR in ~/projects/ckeditor5/node_modules/@isaul32/ckeditor5-math/src/automath.ts(122,24)
      TS2339: Property 'outputType' does not exist on type '{}'.
 @ ../../node_modules/@isaul32/ckeditor5-math/src/math.ts 5:0-34 8:37-45
 @ ../../node_modules/@isaul32/ckeditor5-math/src/index.js 4:0-41 4:0-41
 @ ./src/ckeditor.ts 33:0-62 155:4-15

34 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.90.3 compiled with 34 errors in 22963 ms
```

</details>

**Comment by fedemp** [comment]
I'm sorry, but what command did you run to get such output? I'm sure I've run all available scripts but none has shown any build errors.

From what I see, the `augmentation.d.ts` and `typings-external.d.ts` are not read by the compiler.

**Comment by tony** [comment]
@fedemp Those errors are when using ckeditor5-math via NPM in a [built editor from source](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source)

I don't have a reproducible version of that readily available.

**Comment by tony** [comment]
> From what I see, the augmentation.d.ts and typings-external.d.ts are not read by the compiler.

That clue helped solve it: `.d.ts` weren't being included in the exported package

```diff
diff --git a/package.json b/package.json
index 3f59b3c..b381975 100644
--- a/package.json
+++ b/package.json
@@ -59,7 +59,8 @@
   },
   "files": [
     "lang",
-    "src",
+    "src/**/*.js",
+    "src/**/*.d.ts",
     "build",
     "theme",
     "ckeditor5-metadata.json",
```

Fixed it.

**Review by tony — APPROVED** [review]
@fedemp LGTM



### DLL build

```console
yarn dll:serve
```


image

### Normal build

```yarn start```

image

**Comment by tony** [comment]
@fedemp Live in 41.2.1 ([NPM](https://www.npmjs.com/package/@isaul32/ckeditor5-math/v/41.2.1), [Changelog](https://github.com/isaul32/ckeditor5-math/blob/v41.2.1/CHANGELOG.md), [Release](https://github.com/isaul32/ckeditor5-math/releases/tag/v41.2.1))

Work for you?

**Comment by fedemp** [comment]
So cool that you found the problem in the npmjs builder. I would not have thought of that.

I installed the package and could import it fine.

The only thing I regret is not being able to migrate the tests, but I think it's because ckeditor uses an outdated version of webpack.

**Comment by fedemp** [comment]
BTW, you will have to update the README. 😄

**Comment by tony** [comment]
> The only thing I regret is not being able to migrate the tests, but I think it's because ckeditor uses an outdated version of webpack.

I may be able to take a look. See also #131 

> BTW, you will have to update the README. 😄

Very good catch, I will note the TypeScript support and DLL build as well.

- #133

**Comment by tony** [comment]
@fedemp README updates, live in Live in 41.2.2 ([NPM](https://www.npmjs.com/package/@isaul32/ckeditor5-math/v/41.2.2), [Changelog](https://github.com/isaul32/ckeditor5-math/blob/v41.2.2/CHANGELOG.md), [Release](https://github.com/isaul32/ckeditor5-math/releases/tag/v41.2.2))

**Pull request merged**
