### PR TITLE
Make span element className configurable

### LINKED ISSUE #81: Make span element className configurable
I have a large installation which currently uses the CKEditor 4 MathJax plugin. The plugin provides a configuration for the MathJax element className, which is currently set to the tex2jax.processClass value of the MathJax configuration. I'd like to suggest to have such option here too.

### PR DESCRIPTION
**Pull request by DanielKulbe**
closes #81

### CODE REVIEW

**Comment by tony** [comment]
@DanielKulbe Can you rebase this for 36.0.1 (against master ?)

**Comment by DanielKulbe** [comment]
@tony ... done that

**Comment by tony** [comment]
@DanielKulbe Thanks for the rebase!

**Comment by tony** [comment]
@DanielKulbe Thank you! 

Publishing a release now

**Comment by tony** [comment]
@DanielKulbe Release pending on https://github.com/isaul32/ckeditor5-math/issues/92

P.S. Your website looks excellent

**Comment by tony** [comment]
@DanielKulbe [36.0.5](https://www.npmjs.com/package/@isaul32/ckeditor5-math) is live. If you try it now, how's it work?

**Pull request merged**
